import type { AssetManager } from "../assets/AssetManager";
import type { RuntimeAssetResolverService } from "../assets/RuntimeAssetResolverService";
import type { TextureService } from "../assets/TextureService";
import type { AnimationService } from "../animation/AnimationService";
import type { AudioService } from "../audio/AudioService";
import type { CameraService } from "../camera/CameraService";
import type { AvatarMaterialService } from "../avatar/AvatarMaterialService";
import type { AvatarAssetService } from "../avatar/AvatarAssetService";
import type { CharacterSpawnService } from "../avatar/CharacterSpawnService";
import type { EngineAvatarRuntimeService } from "../avatar/EngineAvatarRuntimeService";
import type { LocalAvatarService } from "../avatar/LocalAvatarService";
import type { AvatarService } from "../avatar/AvatarService";
import type { RemoteAvatarAppearanceService } from "../avatar/RemoteAvatarAppearanceService";
import type { RemotePlayerService } from "../avatar/RemotePlayerService";
import type { RemoteSessionService } from "../avatar/RemoteSessionService";
import type { CommunityProfileService } from "../community/CommunityProfileService";
import type { DebugVisualService } from "../diagnostics/DebugVisualService";
import type { DiagnosticsService } from "../diagnostics/DiagnosticsService";
import type { PerformanceService } from "../diagnostics/PerformanceService";
import type { GameSession } from "../game/GameSession";
import type { EngineInputRuntimeService } from "../input/EngineInputRuntimeService";
import type { InputService } from "../input/InputService";
import type { CharacterCollisionService } from "../movement/CharacterCollisionService";
import type { ClimbService } from "../movement/ClimbService";
import type { EngineLocalPlayerRuntimeService } from "../movement/EngineLocalPlayerRuntimeService";
import type { LocalMovementRuntimeService } from "../movement/LocalMovementRuntimeService";
import type { MovementService } from "../movement/MovementService";
import type { ProtocolService } from "../network/protocol";
import type { MultiplayerService } from "../network/MultiplayerService";
import type { MultiplayerConnectionService } from "../network/relay/MultiplayerConnectionService";
import type { MultiplayerMessageRouter } from "../network/relay/MultiplayerMessageRouter";
import type { MultiplayerSessionService } from "../network/relay/MultiplayerSessionService";
import type { MultiplayerBridgeService } from "../network/bridge/MultiplayerBridgeService";
import type { PacketDebugService } from "../network/PacketDebugService";
import type { SlimService } from "../optimization/SlimService";
import type { PhysicsWorld } from "../physics/types";
import type { ScriptRuntime } from "../scripting/ScriptRuntime";
import type { ClientPhysicsSandbox } from "../sandbox/ClientPhysicsSandbox";
import type { CoreHudService } from "../ui/CoreHudService";
import type { EngineHudRuntimeService } from "../ui/EngineHudRuntimeService";
import type { HudInteractionService } from "../ui/HudInteractionService";
import type { ChatCommandService } from "../ui/ChatCommandService";
import type { ChatService } from "../ui/ChatService";
import type { ChatBubbleService } from "../ui/ChatBubbleService";
import type { LeaderboardService } from "../ui/LeaderboardService";
import type { LeaderboardDomService } from "../ui/LeaderboardDomService";
import type { NotificationService } from "../ui/NotificationService";
import type { RuntimeSettingsPresenterService } from "../ui/RuntimeSettingsPresenter";
import type { SettingsMenuService } from "../ui/SettingsMenuService";
import type { EventBus } from "./EventBus";
import type { EngineCompatibilityService } from "./EngineCompatibilityService";
import type { EngineRuntimeBridgeService } from "./EngineRuntimeBridgeService";
import type { EngineSceneRuntimeService } from "./EngineSceneRuntimeService";
import type { FrameLoopService } from "./FrameLoopService";
import type { LoadingScreenService } from "./LoadingScreenService";
import type { RuntimeSettingsStore } from "./RuntimeSettingsStore";
import type { AccessService } from "../platform/AccessService";
import type { PlatformBridge } from "../platform/PlatformBridge";
import type { QualityService } from "../renderer/QualityService";
import type { RendererService } from "../renderer/RendererService";
import type { SceneSettingsService } from "../renderer/SceneSettingsService";
import type { ShadowRuntimeService } from "../renderer/ShadowRuntimeService";
import type { AssetStreamService } from "../streaming/AssetStreamService";
import type { EngineWorldRuntimeService } from "../world/EngineWorldRuntimeService";
import type { WorldBootstrapService } from "../world/WorldBootstrapService";
import type { WorldService } from "../world/WorldService";
import type { WorldColliderService } from "../world/WorldColliderService";
import type { WorldGeometryService } from "../world/WorldGeometryService";
import type { WorldMaterialService } from "../world/WorldMaterialService";
import type { WorldPartService } from "../world/WorldPartService";
import type { WorldPickingService } from "../world/WorldPickingService";
import type { WorldRuntimeService } from "../world/WorldRuntimeService";
import type { CursorService } from "../input/CursorService";

export type RuntimeEventMap = {
  "vortex:ready": { vortex: unknown };
  "session:changed": { snapshot: unknown };
  "script:package-rejected": { reason: string };
};

export type VortexRuntime = {
  version: string;
  access: AccessService;
  platform: PlatformBridge;
  events: EventBus<RuntimeEventMap>;
  engineCompatibility: EngineCompatibilityService;
  engineRuntimeBridge: EngineRuntimeBridgeService;
  engineScene: EngineSceneRuntimeService;
  frameLoop: FrameLoopService;
  loading: LoadingScreenService;
  settingsStore: RuntimeSettingsStore;
  assets: AssetManager;
  assetResolver: RuntimeAssetResolverService;
  textures: TextureService;
  audio: AudioService;
  camera: CameraService;
  renderer: RendererService;
  sceneSettings: SceneSettingsService;
  shadowRuntime: ShadowRuntimeService;
  engineWorld: EngineWorldRuntimeService;
  world: WorldService;
  worldBootstrap: WorldBootstrapService;
  worldColliders: WorldColliderService;
  worldGeometry: WorldGeometryService;
  worldMaterials: WorldMaterialService;
  worldParts: WorldPartService;
  worldPicking: WorldPickingService;
  worldRuntime: WorldRuntimeService;
  cursor: CursorService;
  engineInput: EngineInputRuntimeService;
  input: InputService;
  characterCollision: CharacterCollisionService;
  climb: ClimbService;
  engineLocalPlayer: EngineLocalPlayerRuntimeService;
  localMovement: LocalMovementRuntimeService;
  movement: MovementService;
  gameSession: GameSession;
  physics: PhysicsWorld;
  avatarMaterials: AvatarMaterialService;
  avatarAssets: AvatarAssetService;
  avatar: AvatarService;
  engineAvatar: EngineAvatarRuntimeService;
  characterSpawn: CharacterSpawnService;
  localAvatar: LocalAvatarService;
  remoteAvatarAppearance: RemoteAvatarAppearanceService;
  remotePlayers: RemotePlayerService;
  remoteSession: RemoteSessionService;
  animation: AnimationService;
  scripting: ScriptRuntime;
  sandbox: ClientPhysicsSandbox;
  slim: SlimService;
  multiplayer: MultiplayerService;
  multiplayerConnection: MultiplayerConnectionService;
  multiplayerBridge: MultiplayerBridgeService;
  multiplayerRouter: MultiplayerMessageRouter;
  multiplayerSession: MultiplayerSessionService;
  packetDebug: PacketDebugService;
  protocol: ProtocolService;
  ui: CoreHudService;
  engineHud: EngineHudRuntimeService;
  hudInteractions: HudInteractionService;
  chatCommands: ChatCommandService;
  chat: ChatService;
  chatBubbles: ChatBubbleService;
  leaderboard: LeaderboardService;
  leaderboardDom: LeaderboardDomService;
  notifications: NotificationService;
  runtimeSettings: RuntimeSettingsPresenterService;
  settingsMenu: SettingsMenuService;
  debugVisuals: DebugVisualService;
  diagnostics: DiagnosticsService;
  perf: PerformanceService;
  community: CommunityProfileService;
  streaming: AssetStreamService;
  quality: QualityService;
  vortex: {
    get(): unknown;
    set(value: unknown): void;
  };
};

export type RuntimeOptions = {
  version: string;
  document: Document;
  window: Window;
  location: Location;
};
